### ISSUE TITLE
Admin cannot use kudo bot normally

### ISSUE THREAD

**Issue by starwaver** [AliceSoft-Inc/kudobot-discord#1]
Right now if an admin DM kudobot /kudo, it gives a list of commands instead of starting the normal bot chat process

Proposed solution:
When typing /kudo in DM (regardless if the user is admin), it should have the conversation normally

**Comment by Tennsoku** [comment]
For current circumstances, an admin user is supposed to have more available commands than non-admin. Therefore the chat interface is only designed for non-admin, and command lines are still open to admin.

**Comment by Tennsoku** [comment]
If you wish to extend the chat interface to admin, further details should be discussed: 
- What should be the interface look like? (More detailed options?)
- New actions to trigger and end command-line mode aside from `/kudo`
- ...

**Comment by starwaver** [comment]
The idea is that the admin can do the exact same actions as normal users, but with a few extra command

No need to have a new interface. The same one works

**Comment by Tennsoku** [comment]
After further discussion, we agree that the command-line mode is not suitable under DM environment. 
From now, command-line mode is only available for public channels, and DM chat interface has extended to all users without permission restriction.
