### ISSUE TITLE
Kudo bot does not recognize some users

### ISSUE THREAD

**Issue by starwaver** [AliceSoft-Inc/kudobot-discord#5]
![image](https://user-images.githubusercontent.com/7750800/87993800-73df5c80-cab9-11ea-9c35-9eae6188581b.png)
See above.

Potential reason might be this user has a space in their username...
![image](https://user-images.githubusercontent.com/7750800/87993844-8eb1d100-cab9-11ea-94ec-e55e10c567a1.png)

**Comment by starwaver** [comment]
Just tried it after asking him to remove space...
![image](https://user-images.githubusercontent.com/7750800/87994166-4e068780-caba-11ea-8581-e5f880263f2b.png)
Still not working

**Comment by Tennsoku** [comment]
This bug is caused by a '!' prefix for users with a unique nickname in the channel. Solved in this commit.
